### ISSUE TITLE
Update Development Roadmap for 6.2, other progress

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#177]
Per multiple Slack threads, including in Marketing channel 

>Hi! https://wordpress.org/about/roadmap/ - needs to be updated with regard to plans for the current year and also "Long term roadmap" part needs at least a change in the time from the future to the past in sentence.

This process is likely documented somewhere in the project. At the least, marketing should be able to answer the question of "who manages X page content?". The answer is usually Meta on a technical level, certainly, but that isn't the same thing as the content level. 

To answer this query, and help complete this update if necessary, Marketing needs to:

- [x] Identify team responsible for updating the WordPress Development Roadmap: https://wordpress.org/about/roadmap/
- [x] If needed, draft updated text
- [x] If needed, update or coordinate with responsible team to update, the WordPress Development Roadmap text 

Admin:

- [ ] Note in Marketing handbook/wiki what team is responsible for Development Roadmap content, update process and any relevant context or links to information elsewhere in project

**Comment by rmartinezduque** [comment]
Hi! @thetinyl  and I have recently worked with @Bringmannn to help update this page. We [drafted this update](https://docs.google.com/document/d/1NvC7a8vh8pFTxFngH4IwD-EEQjpLa6oU5DeYTt2Cjb4/edit#heading=h.1d40ghqbufm7) with relevant goals and initiatives for 2023. The structure follows the [current Roadmap page](https://wordpress.org/about/roadmap/). Chloé told us she’d be happy to help edit the page. We can let her know if any missing/outdated information needs to be changed on that page moving forward.

**Comment by abhansnuk** [comment]
Hello just for some background for the handbook, this page in terms of releases, this is normally updated in the release cycle in core. Thanks to Chloe for responding and updating it too, and to you all for updating it. Once the new version is published, could you let me have the link and I will include it in the highlighted posts in dev chat. Thanks @Bringmannn @rmartinezduque @thetinyl  . Thanks!

**Comment by rmartinezduque** [comment]
Hi @abhansnuk, the new version is already published at https://wordpress.org/about/roadmap/. Some bullet points under APIs and Block theme dev tools are missing due to a code issue—already reported here https://github.com/WordPress/wporg-main-2022/issues/211.

**Comment by abhansnuk** [comment]
Thanks. I have added it to the agenda for today's dev chat. @rmartinezduque .

**Comment by Bringmannn** [comment]
@sereedmedia The Meta team implements updates to the roadmap that are informed by Project leadership, which welcomes feedback from marketing and all make teams.

**Comment by bengreeley** [comment]
> Some bullet points under APIs and Block theme dev tools are missing due to a code issue

@rmartinezduque FYI this issue has been resolved: https://github.com/WordPress/wporg-main-2022/issues/211

**Comment by rmartinezduque** [comment]
Thanks for the update, Ben!

**Comment by OlaIola** [comment]
I cannot translate the updated strings for the Roadmap and write a [question in the Meta team channel on Slack](https://wordpress.slack.com/archives/C02QB8GMM/p1681541180953889) to find if this is an issue or by-effect of Rosetta sites' redesign, and we just need to wait.

**Comment by sereedmedia** [comment]
Closing this ticket as it is completed.
