### ISSUE TITLE
PREP for WC Asia Contributor Day Table - 17 February 2023

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#186]
This ticket is to track all the materials and docs need to prepare leading up to WordCamp Asia Contributor Day, 17 February 2023. 

GitHub Issue for new contributors day-of : [Start Here! New Contributor ticket for WordCamp Asia Contributor Day - February 17 2023 #185](https://github.com/WordPress/Marketing-Team/issues/185) This ticket can also serve as an attendance sheet as such. 

This is the original WCAsia ticket that has been gathering ideas and such since Aug 2022.: [WordCamp Asia 2023 Marketing Table Contributor Day ](https://github.com/WordPress/Marketing-Team/issues/108)https://github.com/WordPress/Marketing-Team/issues/108

## Docs

**Main Contributor Doc**
This doc can be shared with all contributors to help guide them through their day.
https://docs.google.com/document/d/1VQ2fVt1uORoG_dDN9iDNYYcgt7GjW8Udpjr_i4kDhiE/edit?usp=sharing

This doc needs to be updated with the contact information (S/GH/WP) for the table leads and the folks hanging out in Slack.

## Goals

We would like to have a few clear goals for the day. It doesn't have to be three, but maybe two? 

- Onboard new contributors to WP.org, Slack and GitHub
- Goal 2?
- Goal 3?

## Primary Tasks

Identifying a few tasks we'd like folks to accomplish could be productive.

- Introduce yourself on intro ticket #185
- Follow WordPress.org on all social accounts #7 
- Provide feedback or content for at least one ticket marked Good First Issue
- Task 4?

### Good First Issues

These are the GH tickets that are tagged as Good First Issue that we are referring folks to, once they are setup on GH.  

- WordPress Photo Directory Social Campaign - #178 
- Review and provide feedback on Training Team onboarding program and feedback survey - #183 
- Help develop topics and create marketing content for Make WordPress Developer Blog - #171 
- Create single source of reference/FAQ for Make WordPress contributors working on GitHub - #167 

# Tasks
- [x] identify top 3 Goals for the day
- [x] add Goals to Main Contributor Doc
- [x] identify primary Tasks for the day
- [x] add Tasks to Main Contributor Doc
- [x] Finalize all contact information for table leads and marketing team reps on Main Contributor Doc
- [x] Identify or create additional Good First Issue Tickets
- [x] Create post-Contributor Day survey

**Comment by sereedmedia** [comment]
WOW, @santanainniss and I just made some amazing progress over the last three hours of coworking and completed all the things. GO TEAM!!!!! 

I am going to close this issue out. 

- The Day-of docs are all available on the Start Here GH issue here: https://github.com/WordPress/Marketing-Team/issues/185

- The main day doc is here: https://docs.google.com/document/d/1VQ2fVt1uORoG_dDN9iDNYYcgt7GjW8Udpjr_i4kDhiE/edit#

- The WCAsia folder is here: https://drive.google.com/drive/folders/1K14ZnjV2rmIfuPzlGR3mtWeYQhkyDFB3?usp=share_link
