### ISSUE TITLE
Create revised content for GitHub repo Contributor Day Handbook (cross-team collab)

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#192]
## Overview
There is a GitHub repo for a Contributor Day Handbook located at:

- [https://github.com/WordPress/contributor-day-handbook](https://github.com/WordPress/contributor-day-handbook)

This repo could serve as the most up-to-date onboarding process that each team could refer to or use in their handbook content, when onboarding contributors at Contributor Days, and on an ongoing basis. 

However, it is not currently a good resource, as after the many recent updates to WordPress project management processes (GH, etc.) the content it provides is no longer fully up-to-date.

## Tasks

The **content updating** component of this ticket is a good first issue. Editing suggestions should be made directly on this ticket until another dedicated ticket for content is created. Update content by providing text suggestions or linking to a Google doc where your suggestions are made. 

### Content updating (good first issue)
- [ ] Identify what parts of content need to be updated
- [ ] Revise content as needed

### Cross team collab
- [ ] Identify team that managed that GH repo
- [ ] Set up process to coordinate with team to update content
- [ ] Consider beginning x-team conversation/developing a proposal to use this GH as the source doc for onboarding (for use by team, Training, etc.)
- [ ] Finalize content in collaboration with team managing the repo
- [ ] Publish updated content

**Comment by sereedmedia** [comment]
Per @abhansnuk [on Slack here](https://wordpress.slack.com/archives/C02QB8GMM/p1676597262888709), this GH repo has been somewhat split up, partially to the @WordPress/make-community-team and partially to the Training/Learn team.

I'll remove the  good first issue tag for now so we aren't duplicating work until we can identify where the project has landed and if there is already updated content or if this is being managed somewhere else.

**Comment by estelaris** [comment]
I have a lot of updated info collected for WCEU 2023, where should I upload it? And I am happy to write up about lessons learned, which were few but very helpful

**Comment by abhansnuk** [comment]
That's great @estelaris . I would suggest adding it to the existing Contributing Handbook repo so that it can at least be captured and then if anything is needed for particular things in the future, it can be copied from there together with any updates.
