### ISSUE TITLE
Prepare Marketing Team text for WCEU Contributor Day 

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#212]
In addition to preparing for WCEU Contributor Day, we need to pre-prepare a description of the team for the WCEU team. Questions are here:

- [x] - What does the Marketing Make team do?
- [x] - What does Contributor Day look like for your team?
- [x] - What prior knowledge do you expect from new contributors?
- [x] - Which tools will you be using that day? (Slack, Testing sites, WP.org, Figma, etc)
- [x] - How can a new contributor get involved with your team?
- [x] - Is there any follow up from the team with Contributor Day attendees?
- [x] - What is the best thing (more fun, more interesting) about contributing to your team?

### Tasks to Complete this Ticket
- [x] Draft responses to questions 
- [x] Copy responses into WCEU Contributor Day doc here: https://docs.google.com/document/d/19aC3kJF2PF0oSwUYub4K4taxvKVX3fhOHyST5EfF5A0/edit#

**Comment by sereedmedia** [comment]
**What does the Marketing Make team do?**

The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.

**Comment by sereedmedia** [comment]
WordCamp Asia planning docs are in this ticket: https://github.com/WordPress/Marketing-Team/issues/186

**Comment by sereedmedia** [comment]
Alrighty, here is what I've put together. I'll submit to the WCEU team as soon as I get some review. 



**- What does the Marketing Make team do?**

Official Team Description: The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.

Practically, this means that we support Make WordPress community and the various events, initiatives, and resources it produces, such as providing input on release communications. 

**- What does Contributor Day look like for your team?**

For contributors that are already a) signed into WP Slack and b) have a GitHub account:

The Marketing Team manages our tasks via GitHub, so all of our contribution is based around that. After greeting our table leads, contributors will be asked to introduce themselves in the Marketing Slack channel and "check in" by leaving a comment on an introductory GitHub ticket (https://github.com/WordPress/Marketing-Team/issues/225) 

That GitHub issue will lead contributors on a choose-your-own-adventure style exploration through the open Marketing GitHub issues and discussions, where they are encouraged to comment, edit and create marketing materials, or provide ideas as needed. We will have a few issues of special focus throughout the day. A more specific schedule will be available closer to the day of the event.

The Marketing Team will have one table lead available as the primary onsite contact, with additional in-person table leads available throughout the day. Multiple marketing team members will also be available throughout the day on Slack.

 **- What prior knowledge do you expect from new contributors?**
 
We encourage and will support contributors of any skill level who have an interest in marketing and communications. Familiarity with Slack and GitHub is recommended. Ideally, Marketing Team contributors will have experience in marketing concepts such as content creation (writing, video, graphics), strategy, UI/UX, and practical skills such as project management.

 **- Which tools will you be using that day? (Slack, Testing sites, WP.org, Figma, etc)**

We will use GitHub, Slack, Google Docs, Google Sheets, and WP.org.

 **- How can a new contributor get involved with your team?**

Join the table, join the Slack channel, or just start on the introductory GitHub issue.

 **- Is there any follow up from the team with Contributor Day attendees?**

We will be providing a post Contributor Day survey and Slack follow-up!

 **- What is the best thing (more fun, more interesting) about contributing to your team?**

Cross-team collaboration! Most of the Marketing Team members also contribute significantly to a variety of other Make teams across the project, such as Learn, Docs, Core, Community, Meta, and Mobile, and there are ongoing opportunities to work with other Teams.

**Comment by jennimckinnon** [comment]
@sereedmedia Nice job! 🎉 🍪 🙌  

Here's a bit of feedback:

1. What does the Marketing Make team do?

> Official Team Description: The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.
> 
> Practically, this means that we support Make WordPress community and the various events, initiatives, and resources it produces, such as providing input on release communications.

I would take out "Official Team Description" since it's kind of redundant.

The two paragraphs also sound contradictory to my ear. I read it as we create marketing campaigns, but from a practical standpoint, what we _really_ do is release some summaries and newsletters. We do both and that doesn't fully come across to me that way.

What about wording it similar to this:

The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.

We also support the Make WordPress community and the various events, initiatives, and resources it produces, such as through providing input on, writing, and releasing communications.

2. There are some places where the "t" in "team" is capitalized and in other areas where it's not.

3. What does Contributor Day look like for your team?

> For contributors that are already a) signed into WP Slack and b) have a GitHub account:

Maybe add a sentence (or two) that lets new contributors know what to do if they get there and don't have those accounts yet.

> The Marketing Team will have one table lead available as the primary onsite contact, with additional in-person table leads available throughout the day. Multiple marketing team members will also be available throughout the day on Slack.

I would take out "throughout the day" in the part "Multiple marketing team members will also be available throughout the day on Slack." That word is in the previous sentence so removing it the second time sounds better when you read it. Also, marketing team members may not be on Slack the entire day — they may be async, for example.

**Comment by sereedmedia** [comment]
Thank you so much for your feedback @jennimckinnon!

1. I think maybe just using the official team description will be the simplest. 
2. Lowercased all the Ts!
3. Removed the conditional statement. I believe there is a push to have a specific table/area for new contributors onboarding to WP.org, Slack, and GitHub, but if not, we can address this gap closer to the date.
4. I removed the first "throughout the day" and revised slightly.

Revised text below:

**- What does the Marketing Make team do?**

The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.

**- What does Contributor Day look like for your team?**

The Marketing team manages our tasks via GitHub, so all of our contribution is based around that. After greeting our table leads, contributors will be asked to introduce themselves in the Marketing Slack channel and "check in" by leaving a comment on an introductory GitHub ticket (https://github.com/WordPress/Marketing-Team/issues/225) 

That GitHub issue will lead contributors on a choose-your-own-adventure style exploration through the open Marketing GitHub issues and discussions, where they are encouraged to comment, edit and create marketing materials, or provide ideas as needed. 

We will have a few issues of special focus throughout the day. A more specific schedule will be available closer to the day of the event.

The Marketing team will have one table lead available as the primary onsite contact, with additional in-person table leads available. Marketing team members will also be available to greet and support contributors throughout the day on Slack.

 **- What prior knowledge do you expect from new contributors?**
 
We encourage and will support contributors of any skill level who have an interest in marketing and communications. Familiarity with Slack and GitHub is recommended. Ideally, Marketing team contributors will have experience in marketing concepts such as content creation (writing, video, graphics), strategy, UI/UX, and practical skills such as project management.

 **- Which tools will you be using that day? (Slack, Testing sites, WP.org, Figma, etc)**

We will use GitHub, Slack, Google Docs, Google Sheets, and WP.org.

 **- How can a new contributor get involved with your team?**

Join the table, join the Slack channel, or just start on the introductory GitHub issue.

 **- Is there any follow up from the team with Contributor Day attendees?**

We will be providing a post Contributor Day survey and Slack follow-up!

 **- What is the best thing (more fun, more interesting) about contributing to your team?**

Cross-team collaboration! Most of the Marketing team members also contribute significantly to a variety of other Make teams across the project, such as Learn, Docs, Core, Community, Meta, and Mobile, and there are ongoing opportunities to support and work with other teams.

**Comment by sereedmedia** [comment]
Done and dusted.
