### ISSUE TITLE
#WP20 From Blogs to Blocks campaign

### ISSUE THREAD

**Issue by Greennc** [WordPress/Marketing-Team#220]
**#WP20 From Blogs to Blocks** is a contributor-led campaign from the WordPress community celebrating the 20th anniversary of WordPress. 

## Campaign Summary

The **#WP20** From Blogs to Blocks" campaign aims to engage the community to reflect on 20 years of WordPress by encouraging participants to complete 20 WordPress-related actions, such as blogging, building blocks, designing styles/patterns, submitting a photo to #WPPhotos, etc. The campaign will run for 20 days leading up to WordPress 20th Anniversary, from May 7 to May 27, 2023.

The campaign consists of a daily blog post on the Make Marketing P2 featuring prompts that showcase WordPress and reflect on its 20-year history. Each post will include different prompts for developers, designers, photographers, and bloggers. The “blogger” category will include anyone who posts an action on a blog, not just written responses. 

Participants will be encouraged to post links to their actions on their social accounts using the campaign hashtags, and to link to their action as a comment. “Official” participation will be tracked through the comments of the daily Make Marketing post.

Ideally, we could expand the campaign throughout the Make teams by cross-posting the various prompts on the Developer, Design, and Photos P2 blogs, respectively.

## Key Goals

- Celebrating WordPress!
- Promoting community engagement in celebrating 20 years of WordPress **#WP20**
- Promoting contributor engagement in the WordPress community

## Key Performance Indicators

- Participation by contributors 
- Blogs written
- Blocks developed
- Photos posted
- Social posts tagged
- Comments on the Make marketing blog

## Campaign Hashtags

- **#WP20** (official anniversary campaign)
- #BlogsToBlocks (proposed)

## Tasks

- [ ] Create a GitHub ticket for the campaign for centralized planning and collaboration
- [ ] Finalize campaign plan
- [ ] Get feedback from Marketing team and project leadership
- [ ] Incorporate feedback as needed
- [ ] Get final review from Marketing team and project leadership
- [ ] Communicate with other Make teams re cross-posting, prompt suggestions, and participation
    - [ ] Photos
    - [ ] Training
    - [ ] Docs
    - [ ] Dev (Core)
    - [ ] Design
- [ ] Create announcement posts
- [ ] Confirm campaign details
- [ ] Draft and schedule announcement post for Marketing p2
- [ ] Send out campaign information to WP ecosystem media
- [ ] Draft and select 20 prompts for each type of participant
    - [ ] Blog/user prompts
    - [ ] Dev prompts
    - [ ] Design prompts
    - [ ] Photo prompts
- [ ] Create daily Marketing p2 posts with prompts
- [ ] Finalize prompts and publishing order
- [ ] Draft daily posts
- [ ] Post and schedule 
- [ ] Launch the campaign on May 7, 2023

**Comment by nomad-skateboarding-dev** [comment]
Hello! 🙂🙌 Checking in to get assigned.

**Comment by jonathanbossenger** [comment]
Thanks for creating the issue @Greennc and thanks to @sereedmedia for pinging me. I'll do what I can do help here.

**Comment by nomad-skateboarding-dev** [comment]
> purposefully crafted moments to reflect on the journey we've gone on so far, allowing us to percolate and dream of what's to come! 

Thank you for your feedback, and the feelings you shared here @meaganhanes !

I echo those feelings. 🙂 I'm incorporating your thoughts and words here into the Google doc we're currently collaborating on. Thank you. 🙏

I'll be posting that document and today!

**Comment by nomad-skateboarding-dev** [comment]
# #WP20 From Blogs to Blocks campaign prompts document is here for collaboration and feedback! 📣

[Please visit the working Google doc here by clicking on these words.](https://docs.google.com/document/d/1Bzkmx-_hgDGSXaJfJCLkqagWbE3d6OP1Wc1gZ8XGQMA/edit?usp=drivesdk)

Provide your ideas and energy! All contributions welcome! 🎉

**Comment by jennimckinnon** [comment]
I need to catch up on all the suggestions and comments here, but I just thought of an idea and I have to post it before I forget:

I started thinking about how contributing to WordPress has been so impactful to me; not only am I contributing to helping people have an (essentially) guaranteed voice online with self-hosted blogs, but people globally can also create sites for so many things like:

- Self-expression through art, hobbies, and so many other things
- Creating wonderful lives for themselves, their families, and their communities through income generated through online stores, courses, and so much more
- Helping others stay informed about current events, industries, and essentially endless other topics
- Helping fundraise and create awareness for various important causes around the world, and
- What I can only assume Is an endless amount of other types of sites and blogs with various different purposes that better people's lives.

Beyond that and as a contributor to WordPress, I also help others in the community (and globally) learn the ins and outs of WordPress, and we work together to help it shine to the world so we make WordPress make more and more lives better every day.

Then I started thinking about the software itself and how amazing it is just by existing as it is as a piece of tech. But even more than that, the fact that it was co-created and maintained by so many contributors over its 20-year journey.

I think it would be so great if we could have the design team and other teams, and contributors think of a way to artfully display all the contributors through WordPress' 20 years.

One idea I had was to pull data (somehow, TBD) on all the contributors throughout the years and their profile photos (default avatars could be regional or team wappus) and then place them all in a design like a thick font or the logo for the WP20 campaign.

**Comment by sereedmedia** [comment]
Here is the draft of the announcement post: https://docs.google.com/document/d/14-ghDFRkYLK55GsHxvvd3XIIVU7x9-mPxKjwdkpPt3g/edit?usp=sharing

Its been reviewed by @jennimckinnon @nomad-skateboarding-dev and @meaganhanes. More comments and feedback welcome! I intend to post May 1.

**Comment by sereedmedia** [comment]
Made a lil graphic to go with the post. I'll be posting shortly. 
![WP20-FROM-BLOGS-TO-BLOCKS](https://user-images.githubusercontent.com/28426780/235542815-674278ea-55bb-4bc7-95d5-627a2609a0b3.png)

**Comment by sereedmedia** [comment]
@Greennc @jennimckinnon and I met today and did a review and editing session for the prompts. We are almost at 20 for each section, and they are super fun. Need to refine and fill in a few gaps and then move on to drafting and scheduling the posts!

**Comment by sereedmedia** [comment]
**Last Push List**
- [ ] Bring the links over for the dev prompts over to the spreadsheet (hyperlink them)
- [ ] Review and proofread for clarity and context
- [ ] Sort for posting order
- [ ] Add to schedule!

**Comment by sereedmedia** [comment]
@jennimckinnon @nomad-skateboarding-dev and i met today to finalize the prompts, we have 20 for each!!! wooot!

**Comment by meaganhanes** [comment]
Great job team!!

**Comment by sereedmedia** [comment]
we are on day 2! still sorting prompts and finalizing the rest of the schedule 😅 but we are close to letting it run ... and then we all get to participate!!!!!

**Comment by sereedmedia** [comment]
@jennimckinnon et. al., could you help me figure out how folks can contribute to this issue https://github.com/orgs/WordPress/projects/89/views/1?

Per @OlaIola's GH ticket here: https://github.com/WordPress/Marketing-Team/issues/219. It’s a docs project and it needs help to move the mobile docs from dot-com to dot-org along with the Mobile App, but it’s not clear to me how people can do the actual activity of reviewing and pasting the content into somewhere new.

The author of this article: https://make.wordpress.org/mobile/2023/04/11/contribute-to-the-future-of-the-wordpress-app/ 
 said he will update it with additional contribution opportunities, and I'd like to get the docs issue up there before we do the “download the mobile app” prompt.

**Comment by sereedmedia** [comment]
Mostly, I need to know where folks can put the reviewed content before it goes onto dot-org. In the GitHub comments doesn’t seem super helpful. Maybe if there was a google doc linked for each one of these? https://github.com/WordPress/Documentation-Issue-Tracker/issues/787

cc: @estelaris

**Comment by sereedmedia** [comment]
Published links to the first three days:

Day 1: https://make.wordpress.org/marketing/2023/05/08/day-1-wp20-from-blogs-to-blocks/
Day 2: https://make.wordpress.org/marketing/2023/05/09/day-2-wp20-from-blogs-to-blocks/
Day 3: https://make.wordpress.org/marketing/2023/05/10/day-3-wp20-from-blogs-to-blocks/

**Comment by sereedmedia** [comment]
We need to:

- [ ] update the SCHEDULE tab Column F of the [#WP20 From Blogs to Blocks Posting Schedule sheet](https://docs.google.com/spreadsheets/d/14VHwxzRJI58R22qTpOZ08TITespFIciGeujgU_7pzow/edit?usp=sharing) with the links to the published posts. 

- [ ] put into the SCHEDULE tab the final version of the prompt text and links from each published post.

cc: @jennimckinnon @nomad-skateboarding-dev @Greennc

**Comment by jennimckinnon** [comment]
> @jennimckinnon et. al., could you help me figure out how folks can contribute to this issue https://github.com/orgs/WordPress/projects/89/views/1?
> 
> Per @OlaIola's GH ticket here: #219. It’s a docs project and it needs help to move the mobile docs from dot-com to dot-org along with the Mobile App, but it’s not clear to me how people can do the actual activity of reviewing and pasting the content into somewhere new.
> 
> The author of this article: https://make.wordpress.org/mobile/2023/04/11/contribute-to-the-future-of-the-wordpress-app/ said he will update it with additional contribution opportunities, and I'd like to get the docs issue up there before we do the “download the mobile app” prompt.

Commented on it so we can get this moving forward.

I also updated the “SCHEDULE” tab of the Google Sheet with all the prompts up to and including Day 15, including the links to the published posts.

**Comment by estelaris** [comment]
> 
I updated @jennimckinnon on how to work with the reviews of the mobile documentation. At this moment, we only need to review the content: is it still valid? is it up-to-date? outdated? has it been replaced with new feature? etc. 

As soon as I am done with WCEU will get back to the classification because they are all written as FAQs and support answers, not documentation articles. 

So the comments on each of the issues is the best way for us to work on the progress.

**Comment by jennimckinnon** [comment]
Thanks @estelaris! I commented with the necessary steps on [issue #219](https://github.com/WordPress/Marketing-Team/issues/219), except Estela's suggestion is step 2 instead of step 1. But, those are interchangeable and I agree that step 2 (as Estela also mentioned above) can be done first, which will speed up the process. People will be able to contribute even sooner this way. We could have people starting to contribute right away and just promote it straight away in the campaign.

**Comment by DanSoschin** [comment]
Is there anyone collecting (or willing to collect) data on participation? If so, can that be shared? I'd like to recap any participation metrics we have in a post I'm writing to recap all of the WP20 events later in June. Ideally, having the data by Monday June 12 would be preferred, as I plan to write the post that week. Thank you in advance!

**Comment by sereedmedia** [comment]
@DanSoschin yes! that's on my list for this week!
