### ISSUE TITLE
Start Here! New Marketing Team Contributor Issue for WordCamp Europe Contributor Day - 08 June, 2023

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#225]
# Hello and welcome to Contributor Day for WCEU 2023! 

Thank you for being here and contributing to the [Make WP Marketing Team](https://make.wordpress.org/marketing/)!

## Getting Setup

If you're here, that means you're already setup on GitHub. Great! In addition to talking with Marketing team members on-site at Contributor Day, you can ask questions or comment on this issue. The Marketing Team Reps will be monitoring it throughout the day. Also, be sure to sign in to the Marketing channel on Slack.

The Marketing Team manages its projects and operations on GitHub:
- https://github.com/WordPress/Marketing-Team

You can view the GitHub [issues](https://github.com/WordPress/Marketing-Team/issues) and [discussions](https://github.com/WordPress/Marketing-Team/discussions) without a GitHub account. If you’d like to comment on an issue, you will need to [sign up for a GitHub account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account). _Note: Sometimes contributing just looks like providing your input and opinions. Feedback is useful and valuable when working publicly!_

**When you're ready, start here ⬇️**

## Getting started tasks
- [ ] Say hi in the Slack #marketing channel.
- [ ] Introduce yourself in the comments of this GitHub issue. Share what brought you to the Marketing team, your areas of expertise or what interests you most, and what languages you speak and write.
- [ ] Follow the [official WordPress channels](https://github.com/WordPress/Marketing-Team/issues/7) with your social media accounts to help amplify WordPress information and campaigns.
- [ ] Read through the [WordPress Brand Writing Style Guide](https://github.com/WordPress/Marketing-Team/issues/241). (Did you know there is a limit to the amount of exclamation points to use in the WordPress voice?)
- [ ] Check out the [Marketing Team Handbook](https://make.wordpress.org/marketing/handbook/). Updating the Handbook is an ongoing process (ex. [#180](https://github.com/WordPress/Marketing-Team/issues/180) and [#169](https://github.com/WordPress/Marketing-Team/issues/169)  ), so please [share your feedback](https://github.com/WordPress/Marketing-Team/issues/169) after you review.
- [ ] Sign the [WordPress Birthday card](https://make.wordpress.org/marketing/2023/05/27/day-20-wp20-from-blogs-to-blocks/) and check out the Marketing Team's recent campaign [#WP20 From Blogs to Blocks](https://make.wordpress.org/marketing/2023/05/02/20-days-to-celebrate-20-years-of-wordpress-from-blogs-to-blocks/) ([Day 1 is here.](https://make.wordpress.org/marketing/2023/05/08/day-1-wp20-from-blogs-to-blocks/))

## Good first issues to work on during Contributor Day
- [ ] https://github.com/WordPress/Marketing-Team/issues/240: Contributor Day can be a good opportunity to collect testimonials and resources that Marketing can use to promote the diverse voices of WordPress for Pride Month.
- [ ] https://github.com/WordPress/Marketing-Team/issues/222: Share your WordPress growth story or help provide/edit copy to create "social media-sized sound bites" and select imagery for this marketing campaign.
- [ ] https://github.com/WordPress/Marketing-Team/issues/178: You can contribute to this campaign in various ways, from creating social content and collecting WPPhotos stories to capturing marketing photos.

Looking for more areas or tasks to contribute?

- [ ] Check out the [full list of Good First Issues](https://github.com/WordPress/Marketing-Team/labels/good%20first%20issue).
- [ ] Explore all of the [Marketing Team's issues on GitHub](https://github.com/WordPress/Marketing-Team/issues).

## Wrapping up
Before finishing Contributor Day, please take a few minutes to:
- [ ] **Let us know what you worked on** in the comments of this GitHub issue (links are helpful, too). _E.g. I completed onboarding and the getting started tasks, I created some social posts for this campaign [link to GitHub issue], etc._
- [ ] [**Fill out this short form**](https://forms.gle/ZiC5xNb9NC886eKn7) to tell us about your experience at Contributor Day.

**Comment by rmartinezduque** [comment]
Thanks, @goodplansam! I was now able to add you to the GitHub issue :)

**Comment by nikolapuciriusa** [comment]
Hey everyone, I'm Nikola from Indystack. This is my first time participating in WordCamp and contributing.

**Comment by elenafromnitropack** [comment]
Hey fellow Marketers - let's rock it today!
I am Elena from NitroPack and am passionate about everything marketing-related -  campaigns, socials and growth are my main domains.

Excited to collaborate together!











Message marketing









Shift + Return to add a new line
Thread
[marketing](https://wordpress.slack.com/archives/C0GKJ7TFA/p1686209099674999)

**Comment by minalagarwal85** [comment]
Hi everyone! 

I am Minal from Bluehost. I have attended a few WordCamps but this is my first time contributing. I am passionate about everything marketing, currently managing content, social, events for Bluehost. 

Super excited to collaborate!

**Comment by sereedmedia** [comment]
@mrstrande  you might be interested in: https://github.com/WordPress/Marketing-Team/discussions/244

**Comment by lorenzobartoli6992** [comment]
Hi everyone, i'm Lorenzo from ComCart! I've contribute to the Marketing team, it was SUPER! 
It's my first time contributing!

**Comment by sereedmedia** [comment]
Hi all! Thank you for being a part of WCEU Contributor Day! We hope you can join the [Make WP Marketing Slack channel](https://wordpress.slack.com/archives/C0GKJ7TFA) and keep contributing!
