### ISSUE TITLE
Start Here! New Marketing Team Contributor Issue for WordCamp US Contributor Day - August 24, 2023

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#281]
# Hello and welcome to Contributor Day for WCUS 2023! 

Thank you for being here and contributing to the [Make WP Marketing Team](https://make.wordpress.org/marketing/)!

## Getting Setup

If you're here, that means you're already setup on GitHub. Great! In addition to talking with Marketing team members on-site at Contributor Day, you can ask questions or comment on this issue. The Marketing Team Reps will be monitoring it throughout the day. Also, be sure to sign in to the Marketing channel on Slack.

The Marketing Team manages its projects and operations on GitHub:
- https://github.com/WordPress/Marketing-Team

You can view the GitHub [issues](https://github.com/WordPress/Marketing-Team/issues) and [discussions](https://github.com/WordPress/Marketing-Team/discussions) without a GitHub account. If you’d like to comment on an issue, you will need to [sign up for a GitHub account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account). _Note: Sometimes contributing just looks like providing your input and opinions. Feedback is useful and valuable when working publicly!_

**When you're ready, start here ⬇️**

## Getting started tasks
- [ ] Say hi in the Slack #marketing channel.
- [ ] Introduce yourself in the comments of this GitHub issue. Share what brought you to the Marketing team, your areas of expertise or what interests you most, and what languages you speak and write.
- [ ] Follow the [official WordPress channels](https://github.com/WordPress/Marketing-Team/issues/7) with your social media accounts to help amplify WordPress information and campaigns.
- [ ] Read through the [WordPress Brand Writing Style Guide](https://github.com/WordPress/Marketing-Team/issues/241). (Did you know there is a limit to the amount of exclamation points to use in the WordPress voice?)
- [ ] Check out the [Marketing Team Handbook](https://make.wordpress.org/marketing/handbook/). Updating the Handbook is an ongoing process (ex. [#180](https://github.com/WordPress/Marketing-Team/issues/180) and [#169](https://github.com/WordPress/Marketing-Team/issues/169)  ), so please [share your feedback](https://github.com/WordPress/Marketing-Team/issues/169) after you review.
- [ ] Check out the Marketing Team's recent campaign for WordPress' 20th Anniversary [#WP20 From Blogs to Blocks](https://make.wordpress.org/marketing/2023/05/02/20-days-to-celebrate-20-years-of-wordpress-from-blogs-to-blocks/) ([Day 1 is here.](https://make.wordpress.org/marketing/2023/05/08/day-1-wp20-from-blogs-to-blocks/))

## Good first issues to work on during Contributor Day
- [ ] https://github.com/WordPress/Marketing-Team/issues/222: Share your WordPress growth story or help provide/edit copy to create "social media-sized sound bites" and select imagery for this marketing campaign.
- [ ] https://github.com/WordPress/Marketing-Team/issues/280: Collect and combine the onboarding content from each individual Make Team Handbook to compile into universal onboarding document.
- [ ] https://github.com/WordPress/Marketing-Team/issues/178: You can contribute to this campaign in various ways, from creating social content and collecting WPPhotos stories to capturing marketing photos.
- [ ] https://github.com/WordPress/Marketing-Team/issues/279: Help collect the names and WordPress.org handles of participants in the From Blogs to Blocks campaign 

Looking for more areas or tasks to contribute?

- [ ] Check out the [full list of Good First Issues](https://github.com/WordPress/Marketing-Team/labels/good%20first%20issue).
- [ ] Explore all of the [Marketing Team's issues on GitHub](https://github.com/WordPress/Marketing-Team/issues).
- [ ] Ask a Table Lead for ideas.

## Wrapping up
Before finishing Contributor Day, please take a few minutes to:
- [ ] **Let us know what you worked on** in the comments of this GitHub issue (links are helpful, too). _E.g. I completed onboarding and the getting started tasks, I created some social posts for this campaign [link to GitHub issue], etc._
- [ ] [**Fill out this short survey**](https://forms.gle/br6rFskvkkTBvBS68) to tell us about your experience at Contributor Day.

**Comment by jayaw** [comment]
Hi everyone! Looking forward to using git for not-code! Happy WCUS 2023!

**Comment by ExaltoDesigns** [comment]
Hello, My name is Austyn Buchanan. I  have always loved the interactions you get with people in marketing. Thats why im in the marketing group :)

**Comment by radvile-creative** [comment]
Hello, I'm Rad from Hostinger Creatives team. Working on booth set up here in WordCamp and advertising production for Hostinger brand.

**Comment by cshel614** [comment]
Aha... here we are. I'm here saying hi! I'm Carolyn Shelby (cshel), I work at Yoast.

**Comment by suprsam** [comment]
Hi! I'm a first-time WordCamp and Contributor participant. I have experience with all sorts of graphic design and web design and lite marketing strategy. I have my own design agency called Design It Please. I speak and write English (boooorrrriiinnggg).

**Comment by DanSoschin** [comment]
Dan from Tampa, Florida USA... full-time contributor... supporting marketing, some training, comms, and some special projects throughout WP. I enjoy long walks on the beach.

**Comment by austynbuchanan** [comment]
Hello, My name is Austyn Buchanan. I  have always loved the interactions you get with people in marketing. Thats why im in the marketing group :)

**Comment by kmb232** [comment]
Hi! I'm Kathleen and I'm a newbie to WordCamp and Contributor Day. I run my own small business called Anywhere League, so as a small business owner I'm mediocre at all kinds of things. Oh and I live in Washington DC!

**Comment by mjcreative** [comment]
Hi everyone! First time at WordCamp and Contributor day! I have a background in graphic/web design, marketing and development and own a boutique web design agency M|J Creative in Charlotte, NC.

**Comment by AlisonRothwell** [comment]
Hi I’m Alison from WP Fiddly Bits! This is my 6th Contributor Day - I have also volunteered for the People of WordPress project. I’m from the uK, near Manchester ;)

**Comment by rcaldwell16** [comment]
Hi all, I'm Rachel! I'm from California and I'm new to WordCamp. I am the web manager for Chemonics, an international development company and I have a background in communications and marketing. I'm excited to be here! :)

**Comment by aviral-mittal** [comment]
Hello! This is my first WordCamp and Contribution. I work with rtCamp as a marketer. I mainly work on the strategy and help with writing content.

**Comment by vanessapetersen23** [comment]
Hi everyone! I'm Vanessa from the WooCommerce marketing team – I run our blog! I'm from New Hampshire and enjoy reading and triathlon.

**Comment by katydidthat** [comment]
Hello! Kate from GoDaddy here. I work in internal communications, so I'm good with words and stuff. I can copy-edit, write, tell visual stories, and I know Spanish (not a native speaker but took lessons for a good portion of my life). Happy to be here and learn more about marketing!

**Comment by JunebackpocketACE** [comment]
Hello everyone! New to WordPress and returning to work after a long hiatus. Looking forward to learning. I'm from the DC/VA/MD area and enjoy Zentangles.

**Comment by Mattdaddy71** [comment]
Greetings Users! My name is Matt Wagner from Central Florida. I like short walks to the Beach, Tacos and Heavy Metal. Love Me... Or just follow me on LinkedIn 
https://www.linkedin.com/in/matthewswagner/

**Comment by palumbo** [comment]
Hi there 👋🏼 I'm Joseph Palumbo, a long-time WordPress user and former contributor, really interested on how we can grow the WP community and foster better engagement within the community.

**Comment by eidolonnight** [comment]
Hello, everyone! Nicholas from Automattic, typically working from Batavia, NY (US). WordPress user since 2004. A former developer turned marketer.

**Comment by rmartinezduque** [comment]
Closing this issue as completed. As an FYI for the participants/subscribers of this card, the current marketing focus and processes are making a shift toward a new experimental project. Check out the [WordPress Media Corps](https://make.wordpress.org/media-corps/) and [this post](https://make.wordpress.org/media-corps/2024/05/03/wordpress-media-corps-initial-roadmap/) to learn more about it.

Showcase activities are still open to contributions, and you can find out more about them on [GitHub](https://github.com/WordPress/Marketing-Team/wiki/WordPress-Showcase).
