### ISSUE TITLE
Start Here! New Marketing Team Contributor Issue for WordCamp Kathmandu Contributor Day - 08 September 2023

### ISSUE THREAD

**Issue by kafleg** [WordPress/Marketing-Team#294]
नमस्ते, स्वागतम् | 
वर्डक्याम्प काठमाडौँ २०२३ को पहिलो दिनमा यहाँहरु सबैलै स्वागत गर्न पाउँदा धेरै खुसि छौ | 

_Hello and Welcome. 
We are super happy to welcome you all to Contributor Day at WordCamp Kathmandu 2023._ 

-------------------------------------------------------------------------------------

## How We Work
Thank you for your interest in the Make WordPress Marketing Team!

### Contributing to the Marketing Team
The Marketing Team manages its projects and operations on GitHub.

You can view the GitHub [issues](https://github.com/WordPress/Marketing-Team/issues) and [discussions](https://github.com/WordPress/Marketing-Team/discussions) without a GitHub account. If you’d like to comment or contribute to an issue, you will need to [sign up for a GitHub account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account) 

* You can contribute to the Marketing Team by doing work that has been outlined in the various GitHub issues. In some cases this means just adding your feedback (which is **very** useful) or questions.
* Please track any work and link any materials you create on the related GitHub

### Weekly meetings
We conduct a weekly meetings that anyone can attend live or asynchronously every Tuesday at 15:00 UTC. At this meeting we review team and project news and provide a list of active GitHub issues for attendees to review and comment on.

## Get setup

- [ ] 1. Sign up for a GitHub account at [github.com/join](https://github.com/join)
- [ ] 2. Sign up for a WordPress.org account at [login.wordpress.org/register](https://login.wordpress.org/register)
- [ ] 3. Sign up for the Make WordPress Slack at [make.wordpress.org/chat/](https://make.wordpress.org/chat/)
- [ ] 4. Join the [#marketing channel](https://wordpress.slack.com/archives/C0GKJ7TFA) on the Make WordPress Slack 

## Contributor Day tasks
- [ ] Say hi in the Slack #marketing channel.
- [ ] Review [the most recent Marketing Team meeting](https://wordpress.slack.com/archives/C0GKJ7TFA/p1693926107827499) (weekly asynchronous meeting posted in Slack)
- [ ] Introduce yourself in the comments of **this** GitHub issue. Share what brought you to the Marketing team, your areas of expertise or what interests you most, and what languages you speak and write.
- [ ] Follow the [official WordPress channels](https://github.com/WordPress/Marketing-Team/issues/7) with your social media accounts to help amplify WordPress information and campaigns.
- [ ] Read through the [WordPress Brand Writing Style Guide](https://github.com/WordPress/Marketing-Team/issues/241). (Did you know there is a limit to the amount of exclamation points to use in the WordPress voice?)
- [ ] Check out the [Marketing Team Handbook](https://make.wordpress.org/marketing/handbook/). Updating the Handbook is an ongoing process (ex. [#180](https://github.com/WordPress/Marketing-Team/issues/180) and [#169](https://github.com/WordPress/Marketing-Team/issues/169)  ), so please [share your feedback](https://github.com/WordPress/Marketing-Team/issues/169) after you review.

## Good first issues to work on during Contributor Day
Instructions for how to contribute to each issue should be in the issue. If you have questions on a specific issue, you can ask it in the comments of the issue.

- [ ] https://github.com/WordPress/Marketing-Team/issues/282: Have a marketing idea for WordPress but don't know where to put it? Put it here!
- [ ] https://github.com/WordPress/Marketing-Team/issues/222: Share your WordPress growth story or help provide/edit copy to create "social media-sized sound bites" and select imagery for this marketing campaign.
- [ ] https://github.com/WordPress/Marketing-Team/issues/280: Collect and combine the onboarding content from each individual Make Team Handbook to compile into universal onboarding document.
- [ ] https://github.com/WordPress/Marketing-Team/issues/178: You can contribute to this campaign in various ways, from creating social content and collecting WPPhotos stories to capturing marketing photos.
- [ ] https://github.com/WordPress/Marketing-Team/issues/279: Help collect the names and WordPress.org handles of participants in the From Blogs to Blocks campaign 

## Want to do more? 
Here are the main links to view the Marketing Team tasks and projects:

- Check out some of [Good First Issues](https://github.com/WordPress/Marketing-Team/labels/good%20first%20issue) in the Marketing GitHub
- Review the [MakeWP Marketing Team Project Board](https://github.com/orgs/WordPress/projects/21)
- Review [all MakeWP Marketing Team issues](https://github.com/WordPress/Marketing-Team/issues) 

## Before you leave
- [ ] Let us know what you worked on or if you have any questions in the comments of this GitHub issue.
- [ ] Plan to attend the weekly Marketing meeting, either asynchronously or live on Tuesdays @ 15:00 UTC. 
- [ ] Fill out this [short attendee survey](https://forms.gle/BFH7if4cEVRq2mdK8).

**Thank you!**

**Comment by aayushastha** [comment]
Thank you for creating this issue. This will definitely help us on our WordCamp Kathmandu contributor's day Marketing table.

**Comment by kafleg** [comment]
Here is the schedule for Contributor day, https://kathmandu.wordcamp.org/2023/contributor-day-schedule/

**Comment by Dajeema** [comment]
Thank you for creating this issue. It'll be of great help for our WordCamp Kathmandu Contributors Day Marketing Table.

**Comment by rksumit** [comment]
Hello, I am Sumit Thakur. I am here to contribute in marketing team

**Comment by deepaktharu1** [comment]
Hello World

**Comment by GrismaShrestha** [comment]
Thank you for giving us this chance and excited  to learn new things from this session.

**Comment by ayusha788** [comment]
I am excited to join the Marketing team. I am contributing to WordCamp Kathmandu 2023.

**Comment by shreyans-tamang** [comment]
Hello from contributor's table @ WordCamp Kathmandu 2023

**Comment by KritikaSharma** [comment]
Hi, looking forward to contributing to the Marketing team!

**Comment by sweta333** [comment]
Hello I am contributing from WordCamp Kathmandu 2023!!

**Comment by nabincodes** [comment]
I am at the Contributor's table at WordCamp Kathmandu 2023. Excited to learn and contribute.

**Comment by rambknows** [comment]
Hello all, I am at WCKTM2023. Excited to learn and contribute.

**Comment by AlishaBajracharya** [comment]
I am contributing to the Marketing team at WordCamp Kathmandu 2023.

**Comment by raiboby** [comment]
Hi everyone! I' m excited to join and learn with market team at WordCamp Kathmandu 2023..

**Comment by HiraBhattarai** [comment]
I'm contributing from WordCamp Kathmandu from marketing table.

**Comment by kapalimaniraj** [comment]
Hello, I'm contributing from WordCamp Kathmandu 2023 from Marketing Table.

**Comment by imsummit18** [comment]
Hello, I'm contributing from WordCamp Kathmandu 2023 from Marketing Table

**Comment by connectprabin** [comment]
Hello, I am excited to be part of this session.

**Comment by rezis99** [comment]
Hello, I'm Rejish Shrestha contributing to  WordCamp Kathmandu 2023 from Marketing Table.

**Comment by suyogkfl6** [comment]
Hey, Suyog Kafle here, contributing to WordCamp Kathmandu 2023.😉

**Comment by nirsgthfd** [comment]
Hey It's me, Niraj Raut, contributing today at WordCamp Kathmandu 2023

**Comment by Amritburlakoti** [comment]
Hey It's me Amrit Burlakoti, contributing today at WorldCamp Kathmandu 2023

**Comment by iamkumarpradhan** [comment]
Hello, namaste everybody;  Super excited to contribute at WordCamp Kathmandu 2023 today!

**Comment by tenzingsamdup** [comment]
Hi, I'm Tenzing, happy to contribute to WCKTM 2023. I speak English and Nepali. My background is in copywriting, but I've recently got into ui/ux journey. Cheers!

**Comment by shreyans-tamang** [comment]
The email instructions for contributor day included instructions for wordpress.org and Slack accounts, but not for Github. Maybe this should have been there too.

**Comment by sereedmedia** [comment]
> The email instructions for contributor day included instructions for wordpress.org and Slack accounts, but not for Github. Maybe this should have been there too.

Yes absolutely!!! That is something we could probably address in conjunction with this ticket: https://github.com/WordPress/Marketing-Team/issues/295

**Comment by sereedmedia** [comment]
Thank you for your participation. Please join our weekly meetings Tuesdays @ 15:00 UTC in MakeWP Slack, or follow our posts at https://make.wordpress.org/marketing/.
