### ISSUE TITLE
WordPress 6.5 Release Marketing & Communications Plan Overview

### ISSUE THREAD

**Issue by thetinyl** [WordPress/Marketing-Team#356]
This project plan issue tracks and manages marketing activities for the WordPress 6.5 release. It includes a list of expected deliverables and a workback schedule. 

Its main purpose is to keep things organized for Marketing and Communications release leads, @thetinyl and @DanSoschin. Additionally, it’s a way for anyone interested to follow along with the work.

**WordPress 6.5 is scheduled to ship on March 26, 2024.** [View the release calendar.](https://make.wordpress.org/core/6-5/)

Deliverables and assets outlined here follow the recommendations provided in the [Marketing & Communications Release Cycle Guide](https://make.wordpress.org/marketing/handbook/resources/marketing-communications-release-cycle-guide/).

### List of Deliverables

[6.5 MarComms Google Drive](https://drive.google.com/drive/folders/10t6zEKDAMFNgvsc8_-TPy4291ajLigHE?usp=drive_link)

Release milestone announcements on /News:

- [x] Beta 1: https://wordpress.org/news/2024/02/wordpress-6-5-beta-1/
- [x] Beta 2: https://wordpress.org/news/2024/02/wordpress-6-5-beta-2/
- [x] Beta 3: https://wordpress.org/news/2024/02/wordpress-6-5-beta-3/
- [x] Release Candidate (RC) 1: https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-1/
- [x] RC2: https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-2/
- [x] RC3: https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-3/
- [x] RC4 (added late in the release): https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-4/
- [x] General Availability announcement: https://wordpress.org/news/2024/04/regina/

Release marketing content assets:

- [x] About page copy
- [x] Release microsite copy
- [x] Social media promotional content

Creative assets:

- [x] Feature highlight grid → [Tracking issue](https://github.com/WordPress/gutenberg/issues/58028)
- [x] Video featurettes → [Tracking issue](https://github.com/WordPress/gutenberg/issues/58578) 
- [x] Release microsite → [Tracking issue](https://github.com/WordPress/gutenberg/issues/58577)
- [x] Jazzer graphics* 

_*Note: The Jazzer identity and design work is managed by project leadership and delegated to a limited number of individuals. This is to make sure the information is kept confidential until the surprise reveal once the release ships._ 

### Workback Schedule
The dates outlined here are what we, as MarComms leads, will be aiming for. They are subject to change based on the release process and will be kept up to date as things progress. 

| Date  | Deliverables |
| ------------- | ------------- |
31 January | [**Beta 1** draft](https://docs.google.com/document/d/1ZhYA1qVcrlz9WMZ7MKw0dxhDGLHvfP8uXPlayrmYdyQ/edit?usp=sharing) for review
9 February | **Beta 1** draft complete
13 February | [**Beta 1**](https://wordpress.org/news/2024/02/wordpress-6-5-beta-1/)
14 February | [**Beta 2** draft](https://docs.google.com/document/d/1J-YlD7aDMDlHFFeM-uj-dtgmaTYgsScQFYb7_ssx3ZY/edit?usp=sharing) for review
15 February | [**About page** draft](https://docs.google.com/document/d/1YQ7IMQ1n1oyymMvlpM1QVqC-E2Nl3J-_ZQvKSYSL1dM/edit?usp=sharing) for review
19 February | **Beta 2** draft complete
20 February | [**Beta 2**](https://wordpress.org/news/2024/02/wordpress-6-5-beta-2/)
21 February | [**Beta 3** draft](https://docs.google.com/document/d/1DcuIsh_3QoleJQLJYdrDgsuOgWReIDAryoomvzS-6Tw/edit?usp=sharing) for review
26 February | **Beta 3** draft complete
27 February | [**Beta 3** ](https://wordpress.org/news/2024/02/wordpress-6-5-beta-3/)
" | [**About page**](https://github.com/WordPress/wordpress-develop/pull/6182#issuecomment-1965534917) complete
29 February | [**RC1** draft](https://docs.google.com/document/d/14x0yrxPP4-3DT6uirssc0A0M59rJ_IvMrR8BgiYpVXQ/edit?usp=sharing) for review
4 March | **RC1** draft complete
5 March | [**RC1**](https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-1/) _includes a “hard string freeze” + Field guide_
7 March | **RC2** draft for review
11 March | **RC2** draft complete
12 March | [**RC2**](https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-2/)
12 March | [**GA** draft](https://docs.google.com/document/d/10PIHFWGJCRGGQstLm8XWGuFQ1h80CSMFHJ9-oUW3VZE/edit) for review
14 March | [**RC3** draft](https://docs.google.com/document/d/1NOcqxqjYXq_4H0Ka-C2LJA0MsQqCXz8lTLNhU_NHbEY/edit) for review
18 March | **RC3** draft complete
19 March | **RC3**
25 March | Dry Run
" | **GA** draft complete
26 March | **[6.5 Official Release](https://wordpress.org/news/2024/04/regina/)** 🎉

### How to Follow Along
Aside from regular updates to this overview issue, your 6.5 MarComms release leads will be communicating regularly in the [#6-5-release-leads channel](https://wordpress.slack.com/archives/C065MBW03EH) on Slack. 

If you have questions, feel free to reach out to me ([@laurlittle](https://wordpress.slack.com/team/U034VFXCXHB)) and Dan ([@DanSoschin](https://wordpress.slack.com/team/U01UNQ7MMCZ)) in the [#marketing](https://wordpress.slack.com/archives/C0GKJ7TFA) channel on Slack. 

We will be making regular calls to contribute as drafts are ready for review, so if you’re interested in lending a hand—be on the lookout for those!

**Comment by thetinyl** [comment]
As the Beta 1 draft is in progress, I shared a [working list of notable features](https://wordpress.slack.com/archives/C065MBW03EH/p1706214729327679?thread_ts=1706214592.556389&cid=C065MBW03EH) with the release squad for early feedback.

**Comment by thetinyl** [comment]
The [Beta 1 draft](https://docs.google.com/document/d/1ZhYA1qVcrlz9WMZ7MKw0dxhDGLHvfP8uXPlayrmYdyQ/edit?usp=sharing) has been shared with the release squad for review. It's also open to Marketing team for review. 🎉

**Comment by thetinyl** [comment]
### Updates for the week of February 5:

- The [Beta 1 draft](https://docs.google.com/document/d/1ZhYA1qVcrlz9WMZ7MKw0dxhDGLHvfP8uXPlayrmYdyQ/edit?usp=sharing) has been updated and the final review round is in progress. The goal is to get this loaded into the CMS on February 12, to circulate the preview for a last look ahead of the release party scheduled for February 13 at 14:00 UTC. 
- The About page content is slightly delayed in terms of sharing for review. Hoping to have a draft ready for feedback next week.

**Comment by thetinyl** [comment]
The [WordPress 6.5 Beta 1 announcement](https://wordpress.org/news/2024/02/wordpress-6-5-beta-1/) has been shipped! 🚀

**Comment by thetinyl** [comment]
### Updates for the week of February 12

- As noted above, the Beta 1 announcement officially shipped!
- The [Beta 2 announcement post](https://wordpress.org/news/?p=16955&preview=1&_ppp=49fb356033) is in public preview and open for copy edits (due **February 19 at 20:00 UTC**).
- The [About page draft](https://docs.google.com/document/d/1YQ7IMQ1n1oyymMvlpM1QVqC-E2Nl3J-_ZQvKSYSL1dM/edit?usp=sharing) is also ready for review and feedback (due **February 20 at 17:00 UTC**).

**Comment by thetinyl** [comment]
The [WordPress Beta 2 announcement](https://wordpress.org/news/2024/02/wordpress-6-5-beta-2/) has been shipped! 🚀 

Please share and amplify on all your favorite social channels:

[LinkedIn](https://www.linkedin.com/feed/update/urn:li:share:7165760779638562816)
[Tumblr](https://www.tumblr.com/wordpress/742864083457572864/wordpress-65-beta-2)
[Twitter/X](https://twitter.com/WordPress/status/1759995106998776196)
[Facebook](https://www.facebook.com/593573715915605/posts/798914058714902)
[Instagram](https://www.instagram.com/p/C3k--Lss7iI/)

**Comment by DanSoschin** [comment]
Here's a [draft of the Beta 3 post](https://docs.google.com/document/d/1DcuIsh_3QoleJQLJYdrDgsuOgWReIDAryoomvzS-6Tw/edit).

**Comment by thetinyl** [comment]
The [WordPress Beta 3 announcement](https://wordpress.org/news/2024/02/wordpress-6-5-beta-3/) has been shipped! 🚀

Please share and amplify on all your favorite social channels:

- [LinkedIn](https://www.linkedin.com/feed/update/urn:li:share:7168283649887354880/)
- [Tumblr](https://www.tumblr.com/wordpress/743494639123841024/wordpress-65-beta-3)
- [Twitter/X](https://twitter.com/WordPress/status/1762517977918829011)
- [Facebook](https://www.facebook.com/593573715915605/posts/802397878366520)
- [Instagram](https://www.instagram.com/p/C326PZSAJ4f/)

**Comment by thetinyl** [comment]
The WordPress 6.5 Release Candidate 1 announcement has set sail! ⛵ 

Please share and amplify across all your favorite social networks:

- [LinkedIn](https://www.linkedin.com/feed/update/urn:li:share:7170819107242676224/)
- [Tumblr](https://www.tumblr.com/wordpress/744128612185276416/wordpress-65-is-now-in-the-release-candidate?source=share)
- [Twitter/X](https://twitter.com/WordPress/status/1765053437622849782)
- [Facebook](https://www.facebook.com/593573715915605/posts/806024804670494)
- [Instagram](https://www.instagram.com/p/C4I7O9uM0lt/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)
- [@ Threads](https://www.threads.net/@wordpress/post/C4I7PQNiulG)

**Comment by thetinyl** [comment]
### Update for the week of March 4

- [RC1 shipped](https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-1/) earlier in the week!
- [Featurette videos](https://github.com/WordPress/gutenberg/issues/58578) are moving along.
- A couple of [changes for the About page](https://core.trac.wordpress.org/timeline?from=2024-03-08T19%3A47%3A07Z&precision=second) are ready.
- [RC2 draft](https://docs.google.com/document/d/1NzJvLaytWKsggFHIVHeGSjp3jzTcKTZ5UldbIEi3o-Q/edit?usp=sharing) is in review.

**Comment by thetinyl** [comment]
### Update for the week of March 11

- [RC2 shipped](https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-2/) earlier this week! 
- [Featurette videos](https://github.com/WordPress/gutenberg/issues/58578#issuecomment-1994045296) are very close to being complete.
- [RC3 draft](https://docs.google.com/document/d/1NOcqxqjYXq_4H0Ka-C2LJA0MsQqCXz8lTLNhU_NHbEY/edit) is in review.
- [General release draft](https://docs.google.com/document/d/10PIHFWGJCRGGQstLm8XWGuFQ1h80CSMFHJ9-oUW3VZE/edit?usp=sharing) is also in review. 
- [Microsite](https://github.com/WordPress/gutenberg/issues/58577#issuecomment-1991987840) is coming together with some work still in progress.
- [Social teaser visuals](https://github.com/WordPress/gutenberg/issues/58627#issuecomment-1997589131) are in progress.

**Comment by thetinyl** [comment]
Say hello to [WordPress 6.5 "Regina"](https://wordpress.org/news/2024/04/wordpress-6-5-regina/)! First download/update, then remember to share the news with your networks! 

- [LinkedIn](https://www.linkedin.com/feed/update/urn:li:share:7181000948771663872/)
- [Tumblr](https://www.tumblr.com/wordpress/746673734584254464/introducing-wordpress-65-regina-download-and?source=share)
- [Twitter/X](https://twitter.com/WordPress/status/1775235271740539386)
- [Facebook](https://www.facebook.com/593573715915605/posts/821708823102092)
- [Instagram](https://www.instagram.com/p/C5RRZbpsWuK/)
- [@ Threads](https://www.threads.net/@wordpress/post/C5RRapiIIRO)

**Comment by thetinyl** [comment]
With WordPress 6.5 "Regina" released last week, all marketing and communications activities are completed—with social ongoing for the next little while. 

For those who followed along, please share any feedback about the MarComms process for 6.5 as comments in this overview issue. I'll leave it open until **April 15** to collect it all for future release leads. 

🚀

**Comment by thetinyl** [comment]
> For those who followed along, please share any feedback about the MarComms process for 6.5 as comments in this overview issue. I'll leave it open until April 15 to collect it all for future release leads.

Looks like there's no immediate feedback, so I'll close this issue out. 👋
