### ISSUE TITLE
Start Here! New Marketing Team Contributor Issue for WordCamp Asia Contributor Day - March 7, 2024

### ISSUE THREAD

**Issue by bernard0omnisend** [WordPress/Marketing-Team#391]
## Hello and welcome to Contributor Day for WC Asia 2024!
Thank you for being here and contributing to the [Make WP Marketing Team](https://make.wordpress.org/marketing/)!
## Getting set up
If you're here, that means you're already set up on GitHub. Great! In addition to talking with Marketing team members on-site at Contributor Day, you can ask questions or comment on this issue. The Marketing Team Reps will be monitoring it throughout the day. Also, be sure to sign in to the Marketing channel on Slack.

The Marketing Team manages its projects and operations on GitHub:

- https://github.com/WordPress/Marketing-Team 

You can view the GitHub [issues](https://github.com/WordPress/Marketing-Team/issues) and [discussions](https://github.com/WordPress/Marketing-Team/discussions) without a GitHub account. If you’d like to comment on an issue, you will need to [sign up for a GitHub account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account). _Note: Sometimes contributing just looks like providing your input and opinions. Feedback is useful and valuable when working publicly!_

**When you're ready, start here ⬇️**
## Getting started tasks

- [ ] Say “hi” in the Slack #marketing channel.
- [ ] Introduce yourself in the comments of this GitHub issue. Share what brought you to the Marketing team, your areas of expertise or what interests you most, and what languages you speak and write.
- [ ] Follow the [official WordPress channels](https://github.com/WordPress/Marketing-Team/issues/7) with your social media accounts to help amplify WordPress information and campaigns.
- [ ] Read through the [WordPress Brand Writing Style Guide](https://github.com/WordPress/Marketing-Team/issues/241). 
- [ ] Check out the [Marketing Team Handbook](https://make.wordpress.org/marketing/handbook/). Updating the Handbook is an ongoing process, so please [share your feedback](https://github.com/WordPress/Marketing-Team/issues/169) after you review.

## Good first issues to work on during Contributor Day

- [ ] [[Ongoing] WordPress Photo Directory Social Campaign - #WPPhotos #178](https://github.com/WordPress/Marketing-Team/issues/178): You can contribute to this campaign in various ways, from creating social content and collecting WPPhotos stories to capturing marketing photos.
- [ ] [Moderate and help write Showcase entries](https://make.wordpress.org/marketing/handbook/getting-involved/wordpress-showcase/): You can contribute by modering current submissions, sharing your copywriting skills or capturing images from some of the most beautiful sites on the web.
- [ ] [Conduct a survey for WordPress agencies](https://github.com/WordPress/Marketing-Team/discussions/390). Help us understand how agencies and their clients are using WordPress and what their experiences are. Check out the Github discussion for the list of questions and steps for undertaking the survey.
- [ ] [Submit new social media amplification requests](https://github.com/WordPress/Marketing-Team/issues/new?assignees=bjmcsherry%2Ceidolonnight%2Cjennimckinnon%2Cbernard0omnisend%2CGreennc&labels=amplification-request&projects=&template=2-request-for-amplification-template.yml&title=%5BAMPLIFY%5D%3A+) for upcoming events, which includes writing the copy, selecting the images, and providing other necessary items. Amplification is a great way for various WordPress events and campaigns to get more exposure. You can find [a list of upcoming WordPress events here](https://central.wordcamp.org/schedule/), and [an example of a recent Amplification request here](https://github.com/WordPress/Marketing-Team/issues/385). 
- [ ] [Browse through our existing discussions on Github](https://github.com/WordPress/Marketing-Team/discussions) around an area that you’re interested in or have experience with. This can be improvements for things we’re already doing, or new things we aren’t doing yet within Marketing. 
-- If you find a discussion that piques your interest, please engage within the Github discussion thread. 
-- You can also create a new discussion to address a topic that hasn’t been discussed yet. 
-- Alternatively, you can discuss a topic or issue in person, and then create a summary in a Github discussion. 

Looking for more areas or tasks to contribute?

- [ ] Check out the [full list of Good First Issues](https://github.com/WordPress/Marketing-Team/labels/good%20first%20issue).
- [ ] Explore all of the [Marketing Team's issues on GitHub](https://github.com/WordPress/Marketing-Team/issues). 
- [ ] Ask a Table Lead for ideas.

## Wrapping up
Before finishing Contributor Day, please take a few minutes to:

- [ ] Let us know what you worked on in the comments of this GitHub issue (links are helpful, too). _E.g. I completed onboarding and the getting started tasks, I created some social posts for this campaign [link to GitHub issue]_, etc.
- [ ] Fill out [this short form](https://docs.google.com/forms/d/e/1FAIpQLScoSrHLh8G5Licekx9ITdezh8638ikGyZrOggHYxLeEzu2yug/viewform?usp=sf_link) to tell us about your experience at Contributor Day.
- [ ] If you're interested in continuing to contribute to the Marketing team, please attend the Weekly marketing meeting which happens async in the Marketing Slack channel

### The Marketing Team meeting is held weekly in the [Make WordPress #marketing Slack channel](https://wordpress.slack.com/archives/C0GKJ7TFA) on Tuesdays at 15:00 UTC.

**Comment by michael-cannon** [comment]
There's [Get Started with WordPress Social Media #7](https://github.com/WordPress/Marketing-Team/issues/7) too.

**Comment by michael-cannon** [comment]
Howdy folks, I'm Michael, working remotely from Taiwan. I'm leading intelligent automation efforts at Axelerant and was WordPress plugins years back until I went offline publicly. Now, I am coming back around to build awareness of what's possible with empowering people through automation. [More about me](https://peimic.com/about/).

**Comment by marijago** [comment]
Hey! Having contributed to the "Moderate and help write Showcase entries" initiative during WCAsia 2024, I noticed a potential for improvement. 
At the moment we're not communicating to the applicants whose submissions we reject. I believe it would be appropriate to send them a follow-up message explaining the reason for rejection and not leaving them hanging. Some automation could be established between choosing rejection reason in the [Google Sheet](https://docs.google.com/spreadsheets/d/1keMLCjns03DJ9nMTd0E9YSL-I9qFHYLGm_RCRlypY-0/edit#gid=688108543) and sending a message. Wdyt?
Since some entries are from several years back, I would recommend rolling out the follow-up communication only to the fresh submissions (starting from Jan 2024).

**Comment by bernard0omnisend** [comment]
Thank you @michael-cannon for joining the Marketing table for Contributor Day! 

@marijago I think this is a valuable point, and we should move it to a discussion (to explore the idea and come up with a solution), since I'm not sure we have a solution at the moment

**Comment by bernard0omnisend** [comment]
Hi @marijago I moved your point to a new discussion [here](https://github.com/WordPress/Marketing-Team/discussions/406). Hopefully we can get some more folks involved in that discussion and when some clear next-steps are defined, we can create an Issue to address it
